현재 스레드 문제임을 밝힘.

connect는 동기 연결이므로 연결이 성립되어야만 처리되므로 해당 과정에서는 에러가 없음이 확실함.

make_shared로 포인터를 넘기는데, 이 때 넘기는 과정이 에러가 발생할 수 있음


스레드에서 socket을 보낼 때 socket을 sockets[i]에서 for문을 통해서 다시 받아오는데, 이는 주소가 다시 참조되어서 에러가 발생할 수 있음.